trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'azure-vm-ssh'
    runOptions: 'commands'
    commands: |
      cd /home/azureuser/amazon-clone
      git pull origin main
      sudo cp -r * /var/www/html/
      sudo systemctl restart nginx
