trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'azure-vm-ssh'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/home/azureuser/amazon-clone'

- task: SSH@0
  inputs:
    sshEndpoint: 'azure-vm-ssh'
    runOptions: 'commands'
    commands: |
      sudo cp -r /home/azureuser/amazon-clone/* /var/www/html/
      sudo systemctl restart nginx
