trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'azure-vm-ssh'
    runOptions: 'commands'
    commands: |
      pwd
      whoami
      hostname
      cd /home/azureuser/amazon-clone
      pwd
      ls -la
      git status

